name: Psaml static code analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate composer.json and composer.lock
        run: cd backend && composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: backend/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: cd backend && composer install --prefer-dist --no-progress
      - name: Run Psalm init
        run: cd backend && ./vendor/bin/psalm --init
      - name: Run Psalm
        run: cd backend && ./vendor/bin/psalm